name: flutter_google_location_picker
description: A flutter plugin helps to search or pick location picker from map. It is completely free and easy to use.
version: 0.0.3
homepage: https://github.com/arsarsars1/flutter_google_location_picker.git

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  http: ^0.13.5
  latlong2: ^0.8.1
  connectivity_plus: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
